# Generated by Django 4.2.15 on 2024-11-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aplicattion", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="municipio",
            old_name="nombre_dpto",
            new_name="cod_dpto",
        ),
    ]
