# Generated by Django 4.2.16 on 2024-11-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aplicattion", "0002_rename_nombre_dpto_municipio_cod_dpto"),
    ]

    operations = [
        migrations.CreateModel(
            name="fact_clie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplicattion.cliente",
                    ),
                ),
                (
                    "id_fact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplicattion.factura",
                    ),
                ),
            ],
        ),
    ]
